# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

BOARD_TAG    = mega
BOARD_SUB    = atmega2560
MONITOR_PORT = /dev/cu.usbserial-1D160
ARDUINO_DIR  = /Applications/Arduino.app/Contents/Java
ARDMK_DIR    = /usr/local/Cellar/arduino-mk/1.6.0
include /usr/local/Cellar/arduino-mk/1.6.0/Arduino.mk

